#:schema node_modules/wrangler/config-schema.json
name = "email-sender"
main = "src/index.ts"
compatibility_date = "2024-04-05"

dev.host = "127.0.0.1"
dev.port = 8787

[vars]
# 自定义域名的发信邮件地址
# SENDER_EMAIL = "do-not-replay@example.com"
# 发信人简称/名字
# SENDER_NAME = "Example"
